<?php include ("header.php"); ?>
<?php include ("top-navbar.php"); ?>
<?php include ("home-content.php"); ?>
<?php include ("index-all-books.php"); ?>
<?php //include ("featured-books.php"); ?>
<?php //include ("latest-books.php"); ?>
<?php include ("exclusive-content.php"); ?>
<?php include ("authors.php"); ?>
<?php include ("footer.php"); ?>